
INTERRUPT_VECTOR_NMI      = 0xfffa
INTERRUPT_VECTOR_NMI_LO   = INTERRUPT_VECTOR_NMI+0
INTERRUPT_VECTOR_NMI_HI   = INTERRUPT_VECTOR_NMI+1

INTERRUPT_VECTOR_RESET    = 0xfffc
INTERRUPT_VECTOR_RESET_LO = INTERRUPT_VECTOR_RESET+0
INTERRUPT_VECTOR_RESET_HI = INTERRUPT_VECTOR_RESET+1

INTERRUPT_VECTOR_IRQ      = 0xfffe
INTERRUPT_VECTOR_IRQ_LO   = INTERRUPT_VECTOR_IRQ+0
INTERRUPT_VECTOR_IRQ_HI   = INTERRUPT_VECTOR_IRQ+1
