
VIC_BANK0_ADDRESS = 0x0000
VIC_BANK1_ADDRESS = 0x4000
VIC_BANK2_ADDRESS = 0x8000
VIC_BANK3_ADDRESS = 0xc000

VIC_COLOR_BLACK       =  0
VIC_COLOR_WHITE       =  1
VIC_COLOR_RED         =  2
VIC_COLOR_CYAN        =  3
VIC_COLOR_PURPLE      =  4
VIC_COLOR_GREEN       =  5
VIC_COLOR_BLUE        =  6
VIC_COLOR_YELLOW      =  7
VIC_COLOR_ORANGE      =  8
VIC_COLOR_BROWN       =  9
VIC_COLOR_LIGHT_RED   = 10
VIC_COLOR_DARK_GREY   = 11
VIC_COLOR_GREY        = 12
VIC_COLOR_LIGHT_GREEN = 13
VIC_COLOR_LIGHT_BLUE  = 14
VIC_COLOR_LIGHT_GREY  = 15

VIC_SPRITE0_POSITION_X_LO = 0xd000
VIC_SPRITE0_POSITION_Y    = 0xd001
VIC_SPRITE1_POSITION_X_LO = 0xd002
VIC_SPRITE1_POSITION_Y    = 0xd003
VIC_SPRITE2_POSITION_X_LO = 0xd004
VIC_SPRITE2_POSITION_Y    = 0xd005
VIC_SPRITE3_POSITION_X_LO = 0xd006
VIC_SPRITE3_POSITION_Y    = 0xd007
VIC_SPRITE4_POSITION_X_LO = 0xd008
VIC_SPRITE4_POSITION_Y    = 0xd009
VIC_SPRITE5_POSITION_X_LO = 0xd00a
VIC_SPRITE5_POSITION_Y    = 0xd00b
VIC_SPRITE6_POSITION_X_LO = 0xd00c
VIC_SPRITE6_POSITION_Y    = 0xd00d
VIC_SPRITE7_POSITION_X_LO = 0xd00e
VIC_SPRITE7_POSITION_Y    = 0xd00f
VIC_SPRITES_POSITION_X_HI = 0xd010
VIC_CONTROL_SCROLL_Y      = 0xd011
VIC_RASTER_COUNTER        = 0xd012
VIC_LIGHT_PEN_X           = 0xd013
VIC_LIGHT_PEN_Y           = 0xd014
VIC_SPRITES_ENABLED       = 0xd015
VIC_CONTROL_SCROLL_X      = 0xd016
VIC_SPRITES_EXPANSION_Y   = 0xd017
VIC_MEMORY_POINTERS       = 0xd018
VIC_INTERRUPT_REGISTER    = 0xd019
VIC_INTERRUPT_ENABLED     = 0xd01a
VIC_SPRITES_PRIORITY      = 0xd01b
VIC_SPRITES_MCM_ENABLED   = 0xd01c
VIC_SPRITES_EXPANSION_X   = 0xd01d 
VIC_SPRITES_COLLISION     = 0xd01e
VIC_BACKGROUND_COLLISION  = 0xd01f
VIC_BORDER_COLOR          = 0xd020
VIC_BACKGROUND_COLOR0     = 0xd021
VIC_BACKGROUND_COLOR1     = 0xd022
VIC_BACKGROUND_COLOR2     = 0xd023
VIC_BACKGROUND_COLOR3     = 0xd024
VIC_SPRITES_MULTICOLOR0   = 0xd025
VIC_SPRITES_MULTICOLOR1   = 0xd026
VIC_SPRITE0_COLOR         = 0xd027
VIC_SPRITE1_COLOR         = 0xd028
VIC_SPRITE2_COLOR         = 0xd029
VIC_SPRITE3_COLOR         = 0xd02a
VIC_SPRITE4_COLOR         = 0xd02b
VIC_SPRITE5_COLOR         = 0xd02c
VIC_SPRITE6_COLOR         = 0xd02d
VIC_SPRITE7_COLOR         = 0xd02e

# c128 only:
VIC_KEYBOARD  = 0xd02f
VIC_2MHZ_MODE = 0xd030

VIC_COLOR_RAM = 0xd800

vicSpritePointer = lambda a: (a>>6) & 0xff
vicPackedColor = lambda a, b: (a & 0xf) | ((b & 0xf) << 4)
vicPackedScreenCharsetPointer = lambda a, b: (((a & 0x3fff) >> 6) & 0xf0) | (((b & 0x3fff) >> 10) & 0x0e)

VIC_CHARSET_MEMORY_ALIGNMENT = 0x800
VIC_SCREEN_MEMORY_ALIGNMENT  = 0x400
VIC_SPRITE_MEMORY_ALIGNMENT  = 0x40

VIC_SCREEN_WIDTH  = 320
VIC_SCREEN_HEIGHT = 200

VIC_CHAR_COLUMNS = 40
VIC_CHAR_ROWS    = 25

VIC_SPRITE_ORIGIN_X = 24
VIC_SPRITE_ORIGIN_Y = 50

VIC_SPRITE_WIDTH = 24
VIC_SPRITE_HEIGHT = 21

VIC_SPRITE_POINTERS_OFFSET = 0x03f8
VIC_SPRITE0_POINTER_OFFSET = VIC_SPRITE_POINTERS_OFFSET+0
VIC_SPRITE1_POINTER_OFFSET = VIC_SPRITE_POINTERS_OFFSET+1
VIC_SPRITE2_POINTER_OFFSET = VIC_SPRITE_POINTERS_OFFSET+2
VIC_SPRITE3_POINTER_OFFSET = VIC_SPRITE_POINTERS_OFFSET+3
VIC_SPRITE4_POINTER_OFFSET = VIC_SPRITE_POINTERS_OFFSET+4
VIC_SPRITE5_POINTER_OFFSET = VIC_SPRITE_POINTERS_OFFSET+5
VIC_SPRITE6_POINTER_OFFSET = VIC_SPRITE_POINTERS_OFFSET+6
VIC_SPRITE7_POINTER_OFFSET = VIC_SPRITE_POINTERS_OFFSET+7
